# @package _global_

#### Model params #############################################################
model:
  name: gwnet
  hparams:
    residual_channels: 32
    dilation_channels: 32
    skip_channels: 256
    end_channels: 512
    blocks: 2
    layers: 4
    dropout: 0.3
    kernel_size: 2

#### Config overrides ######################################################### 
#### Still need to implement predefined adj for classifaction : supports = [adj]
dataset:
  use_adj: False
